### PR TITLE
Add search engine tags for better visibility :-)

### PR DESCRIPTION
**Pull request by kskarthik**
Thank you for this amazing project !

### CODE REVIEW

**Review by geckolinux — APPROVED** [review]

**Comment by geckolinux** [comment]
Merged. Thanks very much for the contribution, great idea!

**Comment by kskarthik** [comment]
BTW, Just moved to geckolinux static xfce today from Debian unstable. The OS is pretty good.

But,  I faced a tiny permission issue with remaining partitions as they are under root (1000?) group. I fixed this by adding $user to the root group. 

Is this xfce / static specific?

**Comment by geckolinux** [comment]
> But, I faced a tiny permission issue with remaining partitions as they are under root (1000?) group. I fixed this by adding $user to the root group.

Hi there, by "remaining partitions" are you referring to other partitions on the disk not related to GeckoLinux that you're trying to mount?

**Comment by kskarthik** [comment]
Yes

**Comment by geckolinux** [comment]
Does it prompt you for the administrator password to mount them when you click on those partitions in Thunar?

**Comment by kskarthik** [comment]
Mounting them asks for admin pass. But write, deleting files isn't possible on those partitions as they are under root group. So, I added myself to the root group to gain gull access.

**Comment by kskarthik** [comment]
screenshot_2018-01-16_18-29-47

**Pull request merged**
